layout_spectrum: 0.2482466
color:
  saturation: 1
  lightness: 0
  brandStrength: 0.734767
  brandColors:
    - '#FFFFFF'
    - '#125688'
    - '#E1CFBE'
    - '#201615'
    - '#A5A7AA'
  rhythmicContrast: 0.4103943
typography_spectrum: 0.7849463
name: Entretenimientos
